### ISSUE TITLE
Problem when using locale

### ISSUE THREAD

**Issue by meyt** [tytkal/python-hijiri-ummalqura#1]
/umalqurra/hijri_date.py", line 65, in set_date_from_gr
    self.day_name = self.day_dict[self.day_name_en]
KeyError: '\xd8\xac\xd9\x85\xd8\xb9\xd9\x87'

**Comment by tytkal** [comment]
Brother, 
It should work fine. 
can you show the case that happen to you ?

**Comment by meyt** [comment]
```
from umalqurra import hijri_date
import locale

locale.setlocale(locale.LC_ALL, 'fa_IR')  # uncomment this for work fine! this line change datetime library locale too and %A return like جمعه,شنبه... instead of Sun,Fri... 
hdate = hijri_date.HijriDate(2015, 1, 1, True)
print hdate.year, hdate.month, hdate.day  # this line return 1436.0 3.0 10.0! dont need float value for date !
```

**Comment by tytkal** [comment]
OK now it is clear for the first issue supporting local i will merge your branch but you need to fix the issue with day_name_en it should disply the day name in english. 
the date is in float because the algrothm for converting Gergorean to Hijri I can cast it to int but it is the same. 
Thank  you for your contributing.
